[project]
name = "grav_sim"
version = "1.0.1"
description = "N-body gravity simulation library with C and Python API"
readme = "README.md"
authors = [
    { name = "Ching-Yin Ng", email = "alvinng324@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "cmake>=3.10.0",
    "h5py>=3.0.0",
    "matplotlib>=3.8.3",
    "numpy>=1.26.4",
]

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.16.5",
]
