name: Build and upload to PyPI

on:
  push:
    branches: [ test_pypi ]
  release:
    types: [ published ]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [ linux-intel, linux-arm, macOS-intel, macOS-arm ]
        include:
          - archs: auto
            platform: auto
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: macos-intel
            runs-on: macos-13
          - os: macos-arm
            runs-on: macos-latest
            archs: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Clean dist directory
        run: rm -rf dist wheelhouse && mkdir dist wheelhouse

      - name: Install HDF5 and FFTW3 on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install hdf5
          brew install fftw

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_PLATFORM: ${{ matrix.platform }}
          CIBW_ARCHS: ${{ matrix.archs }}
          CMAKE_ARGS: "-DUSE_HDF5=ON -DUSE_FFTW3=ON -DCMAKE_VERBOSE_MAKEFILE=ON"
          CIBW_ENVIRONMENT: "MACOSX_DEPLOYMENT_TARGET=14.0"
          CIBW_BEFORE_BUILD: |
            if [ "${CIBW_PLATFORM}" = "linux" ]; then
              yum install -y hdf5-devel fftw-devel
            fi

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload to PyPI (Release Only)
    needs: [build_wheels, build_sdist]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1

  upload_testpypi:
    name: Upload to TestPyPI (On Commit to test_pypi branch)
    needs: [build_wheels, build_sdist]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
